# Generated by Django 5.0 on 2024-01-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry', '0003_address_returningcitizen_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('parole_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reentry.paroleofficer')),
                ('returning_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reentry.returningcitizen')),
            ],
        ),
    ]
