# Generated by Django 5.0 on 2024-01-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reentry", "0004_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paroleofficer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paroleofficer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
