# Generated by Django 5.0 on 2024-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reentry", "0006_questionnaire_question_userresponse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
